name: PR to inform @quill-icons update

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  Create-PR:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_FULL_NAME: ${{ github.repository }}
      REPO_NAME: ${{ github.event.repository.name }}
      PR_TITLE: 'Create PR from quill-icons-update to master'
      PR_BODY:
        'This pull request is automatically created since a new version of [**@quill-icons**](https://github.com/deriv-com/quill-icons) is available.
        Please review and merge if everything looks good, so that @quill-icons-park can build and deploy.\n
        Generated at $(date).'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{env.REPO_FULL_NAME}}
          token: ${{env.GITHUB_TOKEN}}
          path: ${{env.REPO_NAME}}

      - name: Commit to quill-icons-update branch
        if: success()
        run: |
          echo "${{env.REPO_NAME}} : "
          cd "${{env.REPO_NAME}}"
          echo "time: $(date)"
          git config --global user.email "quill-icons-no-reply@deriv.com"
          git config --global user.name "Quill Icons"
          git checkout -b quill-icons-update
          git pull origin master
          npm version patch -m "build: 🚀 %s installs latest quill icons"
          git push --set-upstream -f origin quill-icons-update

      - name: Create Pull Request
        if: success()
        run: |
          gh pr create --base master --head quill-icons-update --title "${{env.PR_TITLE}}" --body "${{env.PR_BODY}}" --label "Latest @quill-icons"
