name: PR to inform @quill-icons update

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  Create-PR:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_FULL_NAME: ${{ github.repository }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{env.REPO_FULL_NAME}}
          token: ${{env.GITHUB_TOKEN}}
          path: ${{env.REPO_NAME}}

      - name: Set up Git identity
        run: |
          git config --global user.email "quill-icons-no-reply@deriv.com"
          git config --global user.name "Quill Icons"

      - name: Commit to quill-icons-update branch
        if: success()
        run: |
          cd "${{env.REPO_NAME}}"
          git checkout -b quill-icons-update
          git pull origin master
          npm version patch -m "build: 🚀 %s installs latest quill icons"
          git push --set-upstream -f origin quill-icons-update

      - name: Create Pull Request
        if: success()
        run: |
          pr_title = "Create PR from quill-icons-update to master"
          pr_body = "This pull request is automatically created since a new version of [**@quill-icons**](https://github.com/deriv-com/quill-icons) is available.
                    Please review and merge if everything looks good, so that @quill-icons-park can build and deploy.\n
                    Generated at $(date)."
          pr_label = "@quill-icons update available"
          gh pr create --base master --head quill-icons-update --title "$pr_title" --body "$pr_body" --label "$pr_label"
