name: Release

on:
  check_suite:
    types: completed

jobs:
  release:
    name: Send release slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Fetch check suite status
        id: check_suite_status
        run: |
          CHECK_SUITE_CONCLUSION="${{ github.event.check_suite.conclusion }}"
          if [ "$CHECK_SUITE_CONCLUSION" == "success" ]; then
            echo "SLACK_MESSAGE=✅ Quill Icons Park has been updated.\nYou can now browse the latest quill icons at https://quill-icons-park.pages.dev" >> "$GITHUB_OUTPUT"
          else
            echo "SLACK_MESSAGE=❌ Quill Icons Park could not be updated.\nPlease see the details at https://github.com/deriv-com/quill-icons-park/actions" >> "$GITHUB_OUTPUT"
          fi
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR
        with:
          # Authetication token to access GitHub APIs. (Can be omitted by default.)
          # github-token: ${{ github.token }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
          # sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open. (By default it returns PRs in any state.)
          filterOutClosed: true
          # Only return if PR is not in draft state. (By default it returns PRs in any state.)
          filterOutDraft: true
      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl} is ${prJSON}"
        if: steps.PR.outputs.pr_found == 'true'
        env:
          # JSON object with the full PR object
          # toJSON(fromJSON(...pr)) parses it into memory and then format is with pretty-print.
          prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
          # Direct access to common PR properties
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          prLabel: ${{ steps.PR.outputs.pr_labels }}
      # - name: Send Slack Notification
      #   shell: bash
      #   run: |
      #     curl \
      #     -X POST \
      #     -H 'Content-type: application/json' \
      #     --data '{"text": "${{steps.check_suite_status.outputs.SLACK_MESSAGE}}"}' \
      #     ${{ secrets.SLACK_WEBHOOK_URL }}
