name: Release

on:
  check_suite:
    types: completed

jobs:
  release:
    name: Send release slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Fetch check suite status
        id: check_suite_status
        run: |
          CHECK_SUITE_CONCLUSION="${{ github.event.check_suite.conclusion }}"
          if [ "$CHECK_SUITE_CONCLUSION" == "success" ]; then
            echo "SLACK_MESSAGE=✅ Quill Icons Park has been updated.\nYou can now browse the latest quill icons at https://quill-icons-park.pages.dev" >> "$GITHUB_OUTPUT"
          else
            echo "SLACK_MESSAGE=❌ Quill Icons Park could not be updated.\nPlease see the details at https://github.com/deriv-com/quill-icons-park/actions" >> "$GITHUB_OUTPUT"
          fi
      - name: Fetch Open PRs
        run: |
          # Set GitHub API endpoint
          api_endpoint="https://api.github.com/repos/${{github.repository}}/pulls?state=open"

          # Fetch open pull requests using curl
          pull_requests=$(curl -sSL -H "Accept: application/vnd.github.v3+json" "$api_endpoint")

          # Echo the result
          echo "$pull_requests"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Send Slack Notification
      #   shell: bash
      #   run: |
      #     curl \
      #     -X POST \
      #     -H 'Content-type: application/json' \
      #     --data '{"text": "${{steps.check_suite_status.outputs.SLACK_MESSAGE}}"}' \
      #     ${{ secrets.SLACK_WEBHOOK_URL }}
