name: Release

on:
  check_suite:
    types: completed

jobs:
  release:
    name: Send release slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Fetch check suite status
        id: check_suite_status
        run: |
          echo "CHECK_SUITE_CONCLUSION=${{ github.event.check_suite.conclusion }}" >> "$GITHUB_OUTPUT"
          echo "${{steps.check_suite_status.outputs.CHECK_SUITE_CONCLUSION}}"
          if [ "${{steps.check_suite_status.outputs.CHECK_SUITE_CONCLUSION}}" == "success" ]; then
            echo "SLACK_MESSAGE=✅ Quill Icons Park has been updated.\nYou can now browse the latest quill icons at https://quill-icons-park.pages.dev" >> "$GITHUB_OUTPUT"
          else
            echo "SLACK_MESSAGE=❌ Quill Icons Park could not be updated." >> "$GITHUB_OUTPUT"
          fi
          echo "message: ${{steps.check_suite_status.outputs.SLACK_MESSAGE}}"
      - name: Send Slack Notification
        shell: bash
        run: |
          curl \
          -X POST \
          -H 'Content-type: application/json' \
          --data '{"text": "🗂️ Test ${{steps.check_suite_status.outputs.CHECK_SUITE_CONCLUSION}}: ${{steps.check_suite_status.outputs.SLACK_MESSAGE}}' \
          ${{ secrets.SLACK_WEBHOOK_URL_TEST }}
