name: Release

on:
  repository_dispatch:
    types:
      - trigger-workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.0.1
      - name: Build Project
        run: npm run build
      - name: Deploy to Cloudflare
        if: success()
        uses: cloudflare/pages-action@v1.5.0
        with:
          # Cloudflare API Token
          apiToken:
          # Cloudflare Account ID
          accountId:
          # The name of the Pages project to upload to
          projectName:
          # The directory of static assets to upload
          directory:
